### ISSUE TITLE
R2K v3.00 planned features

### ISSUE THREAD

**Issue by skunktober** [vlri4/R2K#2]
- [x] New themes (by myself)
- [x] New themes (by other artists)
- [x] More default profile pictures (for users that don't want to mess with files)
- [x] Launch shortcuts widget from C2K staff
- [x] C2K exchange feed widget from C2K staff
- [ ] Re-code removed calendar widget
- [ ] Planner widget (may be merged with calendar)
- [x] Fixing page names to be easier to understand
- [x] New default logo + theme
- [x] Widget fixes & adjustments

**Comment by skunktober** [comment]
Formerly v2.20, however there are enough features in the upcoming update to make a v3.00.

**Comment by skunktober** [comment]
Calendar / planner will come with other new themes in v3.10.

**Comment by plecakserce** [comment]
https://github.com/plecakserce/R2K/issues/3

**Comment by skunktober** [comment]
R2K v3.10 planned features - https://github.com/plecakserce/R2K/issues/3
